### ISSUE TITLE
Goroutine leakage in newIndirectAsnStore

### ISSUE THREAD

**Issue by dnkolegov** [libp2p/go-libp2p-asn-util#23]
The issue was found by https://github.com/uber-go/goleak.

To reproduce you can start a libp2p node and then try to close it.

The top function is `newIndirectAsnStore`.

```
leaks.go:78: found unexpected goroutines:
        [Goroutine 23 in state runnable, with github.com/libp2p/go-cidranger.(*prefixTrie).insert on top of the stack:
        goroutine 23 [runnable]:
        github.com/libp2p/go-cidranger.(*prefixTrie).insert(0xc0000d1800, {{0xc0018e7740?, 0x4?, 0x4?}, 0x30?}, {0x1974060?, 0xc0018ea5c0})
        	/home/runner/go/pkg/mod/github.com/libp2p/go-cidranger@v1.1.0/trie.go:232 +0x785
        github.com/libp2p/go-cidranger.(*prefixTrie).insert(0xc0000d1380, {{0xc0018e7740?, 0x4a46b7?, 0x1164714?}, 0xc00004dd30?}, {0x1974060?, 0xc0018ea5c0})
        	/home/runner/go/pkg/mod/github.com/libp2p/go-cidranger@v1.1.0/trie.go:264 +0x585
        github.com/libp2p/go-cidranger.(*prefixTrie).insert(0xc000df4d20, {{0xc0018e7740?, 0x4a46b7?, 0x1164714?}, 0xc000df1ce0?}, {0x1974060?, 0xc0018ea5c0})
        	/home/runner/go/pkg/mod/github.com/libp2p/go-cidranger@v1.1.0/trie.go:264 +0x585
        github.com/libp2p/go-cidranger.(*prefixTrie).insert(0xc0009421e0, {{0xc0018e7740?, 0x4a46b7?, 0x1164714?}, 0xc0009411a0?}, {0x1974060?, 0xc0018ea5c0})
        	/home/runner/go/pkg/mod/github.com/libp2p/go-cidranger@v1.1.0/trie.go:264 +0x585
        github.com/libp2p/go-cidranger.(*prefixTrie).insert(0xc0008fc0c0, {{0xc0018e7740?, 0x4a46b7?, 0x1164714?}, 0xc000831420?}, {0x1974060?, 0xc0018ea5c0})
        	/home/runner/go/pkg/mod/github.com/libp2p/go-cidranger@v1.1.0/trie.go:264 +0x585
        github.com/libp2p/go-cidranger.(*prefixTrie).insert(0xc000ccb260, {{0xc0018e7740?, 0x4a46b7?, 0x1164714?}, 0xc000cc99c0?}, {0x1974060?, 0xc0018ea5c0})
        	/home/runner/go/pkg/mod/github.com/libp2p/go-cidranger@v1.1.0/trie.go:264 +0x585
        github.com/libp2p/go-cidranger.(*prefixTrie).insert(0xc0008f5c80, {{0xc0018e7740?, 0x4a46b7?, 0x1164714?}, 0xc00081f8e0?}, {0x1974060?, 0xc0018ea5c0})
        	/home/runner/go/pkg/mod/github.com/libp2p/go-cidranger@v1.1.0/trie.go:264 +0x585
        github.com/libp2p/go-cidranger.(*prefixTrie).insert(0xc0000f06c0, {{0xc0018e7740?, 0x4a46b7?, 0x1164714?}, 0xc0000ee990?}, {0x1974060?, 0xc0018ea5c0})
        	/home/runner/go/pkg/mod/github.com/libp2p/go-cidranger@v1.1.0/trie.go:264 +0x585
        github.com/libp2p/go-cidranger.(*prefixTrie).insert(0xc0000d09c0, {{0xc0018e7740?, 0x4a46b7?, 0x1164714?}, 0xc00004d6b0?}, {0x1974060?, 0xc0018ea5c0})
        	/home/runner/go/pkg/mod/github.com/libp2p/go-cidranger@v1.1.0/trie.go:264 +0x585
        github.com/libp2p/go-cidranger.(*prefixTrie).insert(0xc0000df0e0, {{0xc0018e7740?, 0x4a46b7?, 0x1164714?}, 0xc0000dbb30?}, {0x1974060?, 0xc0018ea5c0})
        	/home/runner/go/pkg/mod/github.com/libp2p/go-cidranger@v1.1.0/trie.go:264 +0x585
        github.com/libp2p/go-cidranger.(*prefixTrie).insert(0xc000093ec0, {{0xc0018e7740?, 0x4a46b7?, 0x1164714?}, 0xc00004cf50?}, {0x1974060?, 0xc0018ea5c0})
        	/home/runner/go/pkg/mod/github.com/libp2p/go-cidranger@v1.1.0/trie.go:264 +0x585
        github.com/libp2p/go-cidranger.(*prefixTrie).insert(0xc0000d12c0, {{0xc0018e7740?, 0x4a46b7?, 0x1164714?}, 0xc00004dcb0?}, {0x1974060?, 0xc0018ea5c0})
        	/home/runner/go/pkg/mod/github.com/libp2p/go-cidranger@v1.1.0/trie.go:264 +0x585
        github.com/libp2p/go-cidranger.(*prefixTrie).insert(0xc0002b41e0, {{0xc0018e7740?, 0x4a46b7?, 0x1164714?}, 0xc00089dbb0?}, {0x1974060?, 0xc0018ea5c0})
        	/home/runner/go/pkg/mod/github.com/libp2p/go-cidranger@v1.1.0/trie.go:264 +0x585
        github.com/libp2p/go-cidranger.(*prefixTrie).insert(0xc0000d5920, {{0xc0018e7740?, 0x4a46b7?, 0x1164714?}, 0xc0000d3630?}, {0x1974060?, 0xc0018ea5c0})
        	/home/runner/go/pkg/mod/github.com/libp2p/go-cidranger@v1.1.0/trie.go:264 +0x585
        github.com/libp2p/go-cidranger.(*prefixTrie).insert(0xc0008ec5a0, {{0xc0018e7740?, 0x4a46b7?, 0x1164714?}, 0xc0000f77e0?}, {0x1974060?, 0xc0018ea5c0})
        	/home/runner/go/pkg/mod/github.com/libp2p/go-cidranger@v1.1.0/trie.go:264 +0x585
        github.com/libp2p/go-cidranger.(*prefixTrie).insert(0xc000a65800, {{0xc0018e7740?, 0x4a46b7?, 0x1164714?}, 0xc000a66c20?}, {0x1974060?, 0xc0018ea5c0})
        	/home/runner/go/pkg/mod/github.com/libp2p/go-cidranger@v1.1.0/trie.go:264 +0x585
        github.com/libp2p/go-cidranger.(*prefixTrie).insert(0xc000c85c20, {{0xc0018e7740?, 0x4a46b7?, 0x1164714?}, 0xc000c87060?}, {0x1974060?, 0xc0018ea5c0})
        	/home/runner/go/pkg/mod/github.com/libp2p/go-cidranger@v1.1.0/trie.go:264 +0x585
        github.com/libp2p/go-cidranger.(*prefixTrie).insert(0xc000bcf620, {{0xc0018e7740?, 0x4a46b7?, 0x1164714?}, 0xc000bd06c0?}, {0x1974060?, 0xc0018ea5c0})
        	/home/runner/go/pkg/mod/github.com/libp2p/go-cidranger@v1.1.0/trie.go:264 +0x585
        github.com/libp2p/go-cidranger.(*prefixTrie).insert(0xc000093500, {{0xc0018e7740?, 0x4a46b7?, 0x1164714?}, 0xc00004c8d0?}, {0x1974060?, 0xc0018ea5c0})
        	/home/runner/go/pkg/mod/github.com/libp2p/go-cidranger@v1.1.0/trie.go:264 +0x585
        github.com/libp2p/go-cidranger.(*prefixTrie).insert(0xc0000935c0, {{0xc0018e7740?, 0x4a46b7?, 0x1164714?}, 0xc00004c950?}, {0x1974060?, 0xc0018ea5c0})
        	/home/runner/go/pkg/mod/github.com/libp2p/go-cidranger@v1.1.0/trie.go:264 +0x585
        github.com/libp2p/go-cidranger.(*prefixTrie).insert(0xc0014727e0, {{0xc0018e7740?, 0x7f58988b6100?, 0x0?}, 0xc00146ff50?}, {0x1974060?, 0xc0018ea5c0})
        	/home/runner/go/pkg/mod/github.com/libp2p/go-cidranger@v1.1.0/trie.go:264 +0x585
        github.com/libp2p/go-cidranger.(*prefixTrie).insert(0xc00009[308](https://github.com/filecoin-project/mir/actions/runs/3372645625/jobs/5596656323#step:4:309)0, {{0xc0018e7740?, 0x10?, 0xc0018e7720?}, 0x10?}, {0x1974060?, 0xc0018ea5c0})
        	/home/runner/go/pkg/mod/github.com/libp2p/go-cidranger@v1.1.0/trie.go:264 +0x585
        github.com/libp2p/go-cidranger.(*prefixTrie).Insert(0xc000093080, {0x1974060, 0xc0018ea5c0})
        	/home/runner/go/pkg/mod/github.com/libp2p/go-cidranger@v1.1.0/trie.go:95 +0x13e
        github.com/libp2p/go-cidranger.(*versionedRanger).Insert(0x15cbcbd?, {0x1974060, 0xc0018ea5c0})
        	/home/runner/go/pkg/mod/github.com/libp2p/go-cidranger@v1.1.0/version.go:29 +0x10f
        github.com/libp2p/go-libp2p-asn-util.newAsnStore()
        	/home/runner/go/pkg/mod/github.com/libp2p/go-libp2p-asn-util@v0.2.0/asn.go:61 +0x1e2
        github.com/libp2p/go-libp2p-asn-util.newIndirectAsnStore.func1()
        	/home/runner/go/pkg/mod/github.com/libp2p/go-libp2p-asn-util@v0.2.0/asn.go:89 +0x8e
        created by github.com/libp2p/go-libp2p-asn-util.newIndirectAsnStore
        	/home/runner/go/pkg/mod/github.com/libp2p/go-libp2p-asn-util@v0.2.0/asn.go:87 +0x117
```

**Comment by marten-seemann** [comment]
I don’t think it’s a leak. It’s just a background go routine that does a bunch of work on startup, and returns once it’s done.

**Comment by dnkolegov** [comment]
Yes, I agree. That was a bug in our code using libp2p.
